version: '3.8'

services:
  postgres_db:
    container_name: postgres_db
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: your_database_name
      POSTGRES_USER: your_database_user
      POSTGRES_PASSWORD: your_database_password
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  web:
    container_name: trainingpage-container
    image: your_website_image:tag
    restart: always
    ports:
      - "80:80"
    depends_on:
      - postgres_db
