version: '3.8'

services:
  postgres_db:
    container_name: postgres_db
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=contact
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password

    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
      
    ports:
      - "5432:5432"
  
  contact:
    container_name: contact
    image: contact
    restart: always
    ports:
      - "8000:8000"
    environment:
      CONTACT_DEFAULT_SERVER: "postgres_db"


# Tape in powerchell : docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' postgres_db
# for access in ip adress to postgres
